/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export default function Car(props: JSX.IntrinsicElements['group']) {
	const group = useRef()
	const { nodes } = useGLTF('/models/car.gltf')
	return (
		<group ref={group} {...props} dispose={null}>
			<group
				position={[0, 149.23, 61.63]}
				rotation={[-Math.PI / 2, 0, 0]}
				scale={[100, 100, 100]}
			>
				<mesh
					castShadow
					receiveShadow
					geometry={nodes.Cylinder.geometry}
					material={nodes.Cylinder.material}
				/>
				<mesh
					castShadow
					receiveShadow
					geometry={nodes.Cylinder_1.geometry}
					material={nodes.Cylinder_1.material}
				/>
				<mesh
					castShadow
					receiveShadow
					geometry={nodes.Cylinder_2.geometry}
					material={nodes.Cylinder_2.material}
				/>
				<mesh
					castShadow
					receiveShadow
					geometry={nodes.Cylinder_3.geometry}
					material={nodes.Cylinder_3.material}
				/>
				<mesh
					castShadow
					receiveShadow
					geometry={nodes.Cylinder_4.geometry}
					material={nodes.Cylinder_4.material}
				/>
				<mesh
					castShadow
					receiveShadow
					geometry={nodes.Cylinder_5.geometry}
					material={nodes.Cylinder_5.material}
				/>
				<mesh
					castShadow
					receiveShadow
					geometry={nodes.Cylinder_6.geometry}
					material={nodes.Cylinder_6.material}
				/>
				<mesh
					castShadow
					receiveShadow
					geometry={nodes.Cylinder_7.geometry}
					material={nodes.Cylinder_7.material}
				/>
				<mesh
					castShadow
					receiveShadow
					geometry={nodes.Cylinder_8.geometry}
					material={nodes.Cylinder_8.material}
				/>
				<mesh
					castShadow
					receiveShadow
					geometry={nodes.lower_grill.geometry}
					material={nodes.lower_grill.material}
					position={[0, -4, -0.57]}
				/>
				<mesh
					castShadow
					receiveShadow
					geometry={nodes.upper_grill.geometry}
					material={nodes.upper_grill.material}
					position={[0, -4.13, 0.17]}
				/>
				<group
					position={[-1.6, 3.08, -0.75]}
					rotation={[0, 0, -Math.PI]}
				>
					<mesh
						castShadow
						receiveShadow
						geometry={nodes.Cylinder002.geometry}
						material={nodes.Cylinder002.material}
					/>
					<mesh
						castShadow
						receiveShadow
						geometry={nodes.Cylinder002_1.geometry}
						material={nodes.Cylinder002_1.material}
					/>
					<mesh
						castShadow
						receiveShadow
						geometry={nodes.Cylinder002_2.geometry}
						material={nodes.Cylinder002_2.material}
					/>
				</group>
				<group position={[1.6, 3.08, -0.75]}>
					<mesh
						castShadow
						receiveShadow
						geometry={nodes.Cylinder002.geometry}
						material={nodes.Cylinder002.material}
					/>
					<mesh
						castShadow
						receiveShadow
						geometry={nodes.Cylinder002_1.geometry}
						material={nodes.Cylinder002_1.material}
					/>
					<mesh
						castShadow
						receiveShadow
						geometry={nodes.Cylinder002_2.geometry}
						material={nodes.Cylinder002_2.material}
					/>
				</group>
				<group
					position={[-1.6, -2.26, -0.75]}
					rotation={[0, 0, -Math.PI]}
				>
					<mesh
						castShadow
						receiveShadow
						geometry={nodes.Cylinder002.geometry}
						material={nodes.Cylinder002.material}
					/>
					<mesh
						castShadow
						receiveShadow
						geometry={nodes.Cylinder002_1.geometry}
						material={nodes.Cylinder002_1.material}
					/>
					<mesh
						castShadow
						receiveShadow
						geometry={nodes.Cylinder002_2.geometry}
						material={nodes.Cylinder002_2.material}
					/>
				</group>
				<group position={[1.6, -2.26, -0.75]}>
					<mesh
						castShadow
						receiveShadow
						geometry={nodes.Cylinder002.geometry}
						material={nodes.Cylinder002.material}
					/>
					<mesh
						castShadow
						receiveShadow
						geometry={nodes.Cylinder002_1.geometry}
						material={nodes.Cylinder002_1.material}
					/>
					<mesh
						castShadow
						receiveShadow
						geometry={nodes.Cylinder002_2.geometry}
						material={nodes.Cylinder002_2.material}
					/>
				</group>
			</group>
		</group>
	)
}

useGLTF.preload('/models/car.gltf')
